name: AQA test task

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull Selenoid browsers
        shell: bash
        run: |
          for browser in $(awk -F'"' '/"image": "/{print $4}' "selenoid/config/browsers.json"); do
            docker pull $browser
          done

      - name: Pull recorder
        shell: bash
        run: |
          docker pull selenoid/video-recorder:latest-release

      - name: Run Selenoid
        shell: bash
        run: |
          docker run -d --name selenoid \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd)/selenoid/config/:/etc/selenoid/:ro \
          -p 4444:4444 \
          aerokube/selenoid:latest-release

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load .env file
        run: |
          cp .env.example .env
          export $(grep -v '^#' .env | xargs)

      - name: Run tests
        run: pytest

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
